<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxctRJD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxctRJD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxctRJD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxctRJD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxctRJD\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxctRJD',
    'container.build_id' => 'b61cfe2f',
    'container.build_time' => 1711022739,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxctRJD');
